#!/bin/bash

for ((arv=1000; arv<=9999; arv++)); do
    praegune=$arv

    # Korratakse numbrite liitmist seni, kuni tulemus on ühekohaline
    while [ $praegune -gt 9 ]; do
        summa=0
        ajutine=$praegune

        # Numbrite eraldamine arvutuslikult ja nende liitmine
        while [ $ajutine -gt 0 ]; do
            summa=$((summa + ajutine % 10))
            ajutine=$((ajutine / 10))
        done

        praegune=$summa
    done

    # Kontrollitakse, kas lõplik ühekohaline arv on 7
    if [ $praegune -eq 7 ]; then
        echo "$arv"
    fi
done
